/* XPM */
static char *logo_data[] = {
/* columns rows colors chars-per-pixel */
"70 60 169 2",
"   c #010101",
".  c #050708",
"X  c #050809",
"o  c #0B0B0B",
"O  c #0A0E10",
"+  c #0D1012",
"@  c #0F191F",
"#  c #131313",
"$  c #141A1C",
"%  c #1B1B1B",
"&  c #141E23",
"*  c #142026",
"=  c #13232B",
"-  c #1D2123",
";  c #1B262B",
":  c #1E292F",
">  c #162A36",
",  c #172D39",
"<  c #1B2C35",
"1  c #1A323E",
"2  c #232324",
"3  c #24292B",
"4  c #2A2B2B",
"5  c #212D33",
"6  c #2F2F30",
"7  c #25353C",
"8  c #283337",
"9  c #2F3A3D",
"0  c #343434",
"q  c #3B3B3B",
"w  c #1C3442",
"e  c #1F3C4C",
"r  c #253942",
"t  c #233D4A",
"y  c #2C3C42",
"u  c #283E48",
"i  c #313D41",
"p  c #2C424C",
"a  c #224253",
"s  c #244659",
"d  c #2A4452",
"f  c #2B4A5A",
"g  c #33434A",
"h  c #36484E",
"j  c #354951",
"k  c #334D59",
"l  c #3C4D53",
"z  c #384F59",
"x  c #3D535B",
"c  c #2B5165",
"v  c #2D586F",
"b  c #2D5870",
"n  c #3D5762",
"m  c #335D73",
"M  c #33617A",
"N  c #38657E",
"B  c #434343",
"V  c #4A4A4A",
"C  c #43555B",
"Z  c #535353",
"A  c #5B5B5B",
"S  c #405B67",
"D  c #4A5E64",
"F  c #47626E",
"G  c #4B646D",
"H  c #476674",
"J  c #486673",
"K  c #4F6B77",
"L  c #53686E",
"P  c #556A71",
"I  c #636363",
"U  c #6B6B6B",
"Y  c #727272",
"T  c #7C7C7C",
"R  c #366883",
"E  c #396B86",
"W  c #41728C",
"Q  c #417591",
"!  c #427D9C",
"~  c #527584",
"^  c #567B8D",
"/  c #5C7D8A",
"(  c #637D85",
")  c #617F8B",
"_  c #5B8294",
"`  c #5A8599",
"'  c #5C899F",
"]  c #4483A5",
"[  c #4787AA",
"{  c #4788AB",
"}  c #4A86A6",
"|  c #4887A8",
" . c #4B8AAD",
".. c #4E8EB0",
"X. c #5D8EA5",
"o. c #508FB1",
"O. c #5E91A9",
"+. c #5392B3",
"@. c #5896B6",
"#. c #5A97B8",
"$. c #5C99B9",
"%. c #65828D",
"&. c #6193AC",
"*. c #6B95A7",
"=. c #6C98AC",
"-. c #6098B4",
";. c #619DBC",
":. c #7097A8",
">. c #779AA7",
",. c #7997A1",
"<. c #64A0BE",
"1. c #6BA0BA",
"2. c #74A2B6",
"3. c #75A6BC",
"4. c #7CA4B4",
"5. c #79A8BC",
"6. c #66A2C0",
"7. c #69A5C2",
"8. c #6EA8C5",
"9. c #70AAC7",
"0. c #73ADC9",
"q. c #7AACC1",
"w. c #76B0CB",
"e. c #7AB3CD",
"r. c #7EB6D0",
"t. c #7FB8D1",
"y. c #828282",
"u. c #8B8B8B",
"i. c #939393",
"p. c #9B9B9B",
"a. c #84A6B2",
"s. c #88AAB4",
"d. c #88AEBC",
"f. c #A3A3A3",
"g. c gray67",
"h. c #B2B2B2",
"j. c #BBBBBB",
"k. c #82B0C5",
"l. c #8BB6C6",
"z. c #83BAD4",
"x. c #88BFD7",
"c. c #88BFD8",
"v. c #99BECA",
"b. c #8CC2DA",
"n. c #90C6DD",
"m. c #93C8DF",
"M. c #9DC5D3",
"N. c #9DCCDE",
"B. c #95CAE0",
"V. c #98CDE3",
"C. c #9DD1E5",
"Z. c #A8D1DE",
"A. c #A7D2E1",
"S. c #A1D5E9",
"D. c #A5D8EC",
"F. c #A9DBEE",
"G. c #ADDEF1",
"H. c #AEE0F2",
"J. c #B4E0EF",
"K. c #B3E3F5",
"L. c #B6E7F8",
"P. c #B7E8F8",
"I. c #BBEAFA",
"U. c #C3C3C3",
"Y. c #C9C9C9",
"T. c #D5D5D5",
"R. c #D8D8D8",
"E. c gray100",
"W. c None",
/* pixels */
"W.W.W.W.              . . .                         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.      # 2 0 B A Z V V B B B q 0 4 3 2 % #                       W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.    2 U y.y.u.u.y.Y I A I U Y T T u.u.i.p.f.f.i.T U Z q % X       .         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.  3 y.y.y.U 3 .       .                     % 4 B A Y u.f.h.f.u.T A B o             W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"    I y.y.B   = m W } #.$.;.-.$.@.&.X.' ` _ ^ H z 7 $ .     o 2 0 A y.h.j.f.T B #     .     W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"  o T y.T . f  ...+.@.#.$.;.<.<.7.8.8.0.w.e.r.z.z.b.b.b.k.*.) G h 3     3 A u.h.U.h.y.Z       W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"  2 y.y.B X ]  ...+.+.#.$.;.<.7.7.7.9.w.w.e.r.z.z.b.b.b.m.B.V.C.C.D.N.>.G 3     2 y.Y.Y.g.# . W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"  0 T y.2 1 {  ...o.+.@.$.;.<.<.7.8.0.0.w.e.r.z.z.b.b.b.m.B.V.C.C.D.D.F.J.K.F.a.C   I Y.Y.p.    W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"  V T y.+ s {  ...+.@.@.$.;.<.<.7.7.0.0.e.e.r.z.z.c.b.b.2.K x 7 ; - 5 8 y g l C D 9 . I i.h.q   W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"  Z T y.  b {  ...o.+.#.$.-.<.<.7.8.8.0.w.e.e.z.z.c.5.g   # 2 0 V B B B q q 0 0 4 3 % o         .           W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
". B T T   M {  ...o.+.#.$.;.<.<.7.8.0.0.w.e.e.r.z.b.7 # A y.y.Z q 4 % & - 4 0 0 q B V A U Y U L V 6 %               W.W.W.W.W.W.W.W.W.W.W.W.",
". q T y.  b {  ...+.+.@.$.$.<.<.7.7.0.0.e.e.z.z.z.3.  A y.A o X * 7 f k d p p r 7 < : % .     o 2 q Z U y.y.A 2     .     W.W.W.W.W.W.W.W.W.",
"  0 y.y.O c {  .o.o.+.$.$.$.<.<.7.7.8.0.e.e.e.t.z.J o y.T O w { o.+.$.$.;.<.7.8.w.e.e.z.z.5.*./ G j 5 o   o 0 U p.u.I 4       W.W.W.W.W.W.W.",
"  4 T y.# s { {  .o.+.+.$.$.<.<.7.8.8.0.w.e.e.z.z.j 2 y.Z . !  .+.@.$.$.6.<.8.8.w.w.e.z.z.b.b.m.B.V.C.D.l.%.l $   o y.Y.u.    W.W.W.W.W.W.W.",
"  2 T y.% e {  .o.o.+.$.$.;.<.<.<.8.8.0.w.e.t.z.z.: 0 T q & { o.o.+.$.$.<.6.<.8.0.w.e.t.z.b.b.m.B.V.C.S.D.G.H.K.M.L   u.Y.A     W.W.W.W.W.W.",
"  % T y.2 w {  .o.o.+.+.$.$.<.<.7.8.8.0.w.e.e.z.z.& B y.4 w  . .o.+.$.$.<.6.8.8.0.w.e.z.z.b.b.b.B.V.C.D.F.F.H.K.P.I.C 2 Y.f.    W.W.W.W.W.W.",
"  # T y.4 , { { o.o.+.#.#.$.;.<.7.8.8.0.w.e.r.r.z.5 q y.2 t {  .+.+.#.$.<.<.7.8.0.w.r.t.z.c.b.b.B.V.C.D.D.G.G.K.P.I.s.  j.j.    W.W.W.W.W.W.",
"  . T y.0 = {  . .o.+.#.#.;.<.<.<.8.8.0.w.w.e.z.z.7 6 T 3 w {  . .+.#.$.<.<.7.8.0.0.e.t.z.b.b.m.B.V.C.C.D.G.F.K.P.I.v.  h.Y.    W.W.W.W.W.W.",
"    Y y.Z . | {  .+.+.@.$.$.<.<.7.8.8.0.w.e.e.z.z.g 4 T 0 > [  .+.+.@.$.;.<.7.8.0.w.e.t.x.x.b.b.V.V.C.D.D.D.H.K.P.I.A.  f.T..   W.W.W.W.W.W.",
"    Z T Y   R  . .o.+.+.#.$.;.<.<.8.8.0.w.w.e.z.z.z 2 y.q & [  .+.+.@.$.<.<.7.8.0.w.r.t.z.x.b.B.B.V.C.C.D.G.H.K.P.I.K.  i.Y.o   W.W.W.W.W.W.",
"W.  0 y.y.+ s  . .o.+.@.$.$.;.<.<.8.8.8.0.w.e.z.z.n & y.B @ {  . .+.@.$.6.<.7.8.0.0.r.r.z.x.b.b.B.V.C.C.G.G.H.K.L.I.M.  g.j.    W.W.W.W.W.W.",
"W.  + y.y.4 = | o.o.+.@.@.;.;.<.7.7.8.0.w.w.e.z.z.H # y.V + {  .+.+.@.$.;.<.7.8.9.w.e.t.z.x.b.b.m.V.C.D.D.F.H.H.L.I.,.o Y.p.    W.W.W.W.W.W.",
"W.    Y y.Z . |  .o.o.@.#.$.;.<.<.8.8.0.w.e.e.z.z.~ . T A   ] {  .+.@.$.;.<.7.7.0.w.e.r.z.x.b.n.B.B.C.C.D.F.F.K.L.I.L 6 Y.Y . W.W.W.W.W.W.W.",
"W.    Z y.Y   E  .o.+.+.$.$.;.<.<.7.8.0.0.e.e.r.z.2.  I T   N  ...+.@.$.$.<.7.8.0.0.e.t.z.x.b.b.m.V.C.C.D.D.H.K.L.P.9 A Y.V   W.W.W.W.W.W.W.",
"W.W.  0 y.u.+ a  .o.+.+.#.$.;.;.7.7.8.0.w.w.e.z.z.z.+ B y.% e  ...+.@.#.$.<.7.8.9.0.e.r.z.x.b.n.B.V.V.D.D.F.F.K.L.Z.  u.Y.%   W.W.W.W.W.W.W.",
"W.W.  # y.y.B o | o.+.+.#.$.;.<.<.8.8.0.0.e.e.z.z.z.g 3 y.q * {  .+.@.$.$.6.6.8.0.w.r.r.z.z.b.b.m.V.C.C.D.G.H.K.L.( # Y.p.    W.W.W.W.W.W.W.",
"W.W.    U y.T   c  .+.+.@.$.;.<.<.7.8.0.0.w.e.t.z.z.K o T A   } o.+.@.#.$.<.7.8.0.0.e.r.z.z.b.n.m.B.C.C.C.G.G.H.H.& A Y.V   W.W.W.W.W.W.W.W.",
"W.W.W.  4 u.y.B o Q +.@.@.$.;.<.<.7.8.8.1.&.` ~ H n y   U T   M ..+.@.$.$.6.6.8.8.0.e.r.z.z.b.b.m.B.C.C.D.D.F.d.i . g.U.o   W.W.W.W.W.W.W.W.",
"W.W.W.    Y y.u.2   O + & & = < < * o           # 2 0 o B y.3 =  .+.+.$.$.6.<.7.8.w.e.e.z.x.b.b.m.V.n.4.( C #   3 f.j.B     W.W.W.W.W.W.W.W.",
"W.W.W.    3 y.u.y.Z Z V V B B q q V A U T u.p.g.g.f.i.0 # y.U   R +.+.$.<.6.6.8.0.w.e.e.3.=._ F y &     + 0 I f.i.Z o     W.W.W.W.W.W.W.W.W.",
"W.W.W.W.    q U T u.u.u.i.u.i.y.T U I Z B 0 2 # .         A y.0 . < w u d k f u 5 & O         2 B I T y.Y Z 3 .   .     W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.                          . o # 2 2 .         . # y.y.q 0 4 4 2 - 3 0 B Z I U Y Y Y A q #       .       W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.                  4 A U Y T T Y .     W.W.W.    % 0 q B B V Z Z B 0 2 # o         .         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.    Y T y.y.u.i.3     W.W.W.W.W.            . . . # 2 4 q 0         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.  % i.p.p.f.f.U     W.W.W.W.W.W.W.W.W.W.W.W.    B T T u.y.o     W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.    A h.h.j.j.U.Z     W.W.W.W.W.W.W.W.W.W.W.W.    u.p.f.f.B .   W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.    p.Y.Y.U.j.j.Y   .       W.W.W.W.W.W.W.W.W.  2 j.j.U.Y.q       W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.    Z g.g.g.f.p.p.y.B 2         W.W.W.W.W.W.W.  0 j.h.h.g.Y #         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.    0 u.i.u.y.T T T Y U Z o   W.W.W.W.W.W.W.    0 i.i.u.y.T U V 2     W.W.W.W.W.W.W.W.W.W.W.  . # # # #   W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.    . 0 I U I I Z q 4 #     W.W.W.W.W.W.W.W.      % B A V 0 % .     W.W.W.W.W.W.W.W.W.W.  . 2 q 2 A u.2 #   W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.        . o             W.W.W.W.W.W.W.W.W.W.                    W.W.W.W.W.W.W.W.W.W.  o g.Y.u.2 U.R.R.f.#   W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.              W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.      W.W.W.W.W.W.W.W.W.W.W.W.W.W.  o # 2 4 i.T.R.R.T.h.+   ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.        . . .     W.W.W.W.W.  o T # + 2 h.R.R.R.T o ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.            . 0 Z A I Z       W.W.W.W.  o I j.. + Y R.R.U.o ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.      .     6 I u.g.U.U.T p.u.q A %     W.W.W.W.  o + I f.o I R.R.o ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.      .     2 A i.j.U.U.y.q p.T 6 2 i.q 0 g.4     W.W.W.W.W.  o o 2 3 A i.o ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.        . Z u.g.y.h.g.4 % f.q B # h.T U U f.V 3 y.0     W.W.W.W.W.W.W.  o . o   ",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.  . U %   Y j.# B 2 f.3 q 2 j.Y T A g.A 0 2 i.q I f.4     W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    Y Y.U.0   I y.% # T h.y.U B g.3 B 2 h.U I I p.# 6 p.#   W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    f.Y.Y.Y.Z . A g.T % 2 p.# Z 2 h.Z I U j.4 q B y.I T p.    W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    u.Y.Y.Y.Y.I   A T 4 4 0 g.B I Y h.o Z B j.I I i.4 4 I Z   W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.  # U.Y.Y.Y.Y.A . y.u.Y I T p.o V Z f.q I f.T 4 2 p.Y h.i.    W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    B U.Y.Y.Y.Y.0 . g.V 4 0 Y T # A h.Y 3 4 g.y.T j.Y.U.I     W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    4 j.Y.Y.Y.U.% 2 j.0 % I Y.y.% 2 g.B 0 u.Y.Y.U.u.%       W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    % h.Y.Y.Y.h.. Z U.U % A f.2 4 V Y.U.Y.j.U #       W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.  . o y.Y.Y.Y.T . p.0 Z + Y g.f.U.Y.f.V         W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.      q h.Y.Y.% B U.Z Y j.Y.j.Y 2         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.    o Y j.y.  j.Y.U.y.q         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.        4   B 4 o         W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.",
"W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.        .       W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W.W."
};
